In [1]:
import numpy as np

In [2]:
j=[5,45,42,65,64,25,14,254,124,6,5,54,2,5]
j

[5, 45, 42, 65, 64, 25, 14, 254, 124, 6, 5, 54, 2, 5]

In [3]:
np.array([5,45,42,65,64,25,14,254,124,6,5,54,2,5])

array([  5,  45,  42,  65,  64,  25,  14, 254, 124,   6,   5,  54,   2,
         5])

In [4]:
np.mean(j)

50.714285714285715

In [5]:
np.median(j)

33.5

In [6]:
np.quantile(j,0.25)

5.25

In [7]:
r=np.random.rand(500)

In [8]:
r

array([0.38885776, 0.8965081 , 0.75529131, 0.87945104, 0.38327549,
       0.14017576, 0.4916773 , 0.30053512, 0.8671036 , 0.95277942,
       0.58499117, 0.5373151 , 0.45590897, 0.53424657, 0.76895689,
       0.38232558, 0.70568369, 0.12559485, 0.72726518, 0.33682824,
       0.51259106, 0.08604267, 0.60822916, 0.44370454, 0.91445782,
       0.45475338, 0.82546389, 0.60350551, 0.03104397, 0.85811799,
       0.37284593, 0.62237429, 0.17173187, 0.87597104, 0.87070819,
       0.45754218, 0.51619855, 0.79721263, 0.59859248, 0.55570094,
       0.77762304, 0.59754566, 0.10468845, 0.2398092 , 0.60153384,
       0.16979457, 0.9964112 , 0.11434777, 0.65089226, 0.89232147,
       0.30634193, 0.6612966 , 0.91580985, 0.93802768, 0.20604926,
       0.97989322, 0.0278312 , 0.07019115, 0.67939085, 0.89604033,
       0.15776512, 0.85967914, 0.64835672, 0.69014252, 0.56371661,
       0.31806416, 0.36944361, 0.0306617 , 0.84872074, 0.08388882,
       0.85438659, 0.27568313, 0.13402335, 0.68333879, 0.91627

In [10]:
np.random.rand(50,10)

array([[1.06629016e-01, 8.69252045e-01, 4.87018786e-03, 1.74595726e-03,
        7.68810733e-01, 4.20702598e-01, 6.52423601e-01, 8.30503434e-01,
        5.80455854e-01, 2.06663596e-02],
       [1.02072696e-02, 4.52230334e-01, 3.56603505e-01, 8.80400346e-02,
        1.69415801e-01, 9.82151272e-02, 8.11777685e-01, 3.70272911e-01,
        2.88269498e-01, 7.63350144e-01],
       [4.35410998e-01, 3.27918420e-01, 5.99041236e-02, 4.38134800e-01,
        2.63170903e-01, 5.20421291e-02, 9.48732445e-01, 1.99390691e-01,
        3.73847232e-01, 7.35894866e-01],
       [8.49848968e-01, 6.64807056e-01, 4.38547040e-01, 8.87071708e-01,
        8.90292436e-01, 5.58370627e-01, 3.59393591e-01, 2.18407325e-01,
        5.65108590e-01, 7.14797898e-01],
       [7.34130850e-01, 6.22326128e-01, 7.81804237e-01, 7.35101859e-01,
        3.03924067e-01, 3.51656421e-01, 2.44543608e-01, 4.21269222e-01,
        1.01579658e-01, 3.15836529e-01],
       [6.39143725e-01, 7.99112521e-01, 2.51231621e-01, 6.70540274e-01,
   

In [9]:
r.size

500

In [14]:
np.random.normal(10,2,(7,4))

array([[ 8.52256437, 10.07825879,  8.61452055, 14.48503787],
       [ 8.4171545 ,  8.87727763,  9.89438116,  8.40004714],
       [ 8.58985865,  8.23755828, 10.02293324, 10.34279885],
       [10.79575366,  9.90535864,  8.7313309 ,  5.37751549],
       [ 9.64233904,  9.1610895 ,  6.86194419,  9.77211383],
       [10.92791661, 10.72314276,  9.60164242,  9.41247517],
       [12.40095131,  8.15516742,  9.04395322, 10.8260637 ]])

In [15]:
np.random.randint(35,86,200)

array([42, 39, 42, 52, 56, 42, 51, 84, 50, 60, 40, 65, 57, 74, 61, 61, 54,
       53, 66, 62, 68, 57, 80, 51, 61, 64, 68, 40, 84, 57, 54, 64, 56, 59,
       49, 74, 84, 76, 36, 63, 64, 47, 45, 76, 85, 53, 50, 71, 78, 62, 35,
       75, 40, 82, 52, 63, 84, 54, 39, 52, 56, 67, 47, 71, 51, 54, 53, 36,
       65, 78, 39, 60, 45, 43, 66, 69, 64, 85, 81, 54, 52, 74, 35, 68, 77,
       49, 67, 54, 50, 47, 60, 63, 75, 47, 77, 62, 47, 63, 53, 80, 71, 79,
       45, 58, 67, 72, 67, 70, 49, 47, 49, 57, 36, 71, 63, 37, 66, 80, 48,
       47, 71, 54, 77, 74, 82, 51, 49, 53, 62, 36, 74, 51, 76, 78, 77, 62,
       50, 48, 45, 68, 43, 74, 76, 73, 37, 35, 85, 67, 50, 80, 60, 57, 77,
       53, 69, 58, 60, 48, 67, 63, 61, 82, 46, 57, 67, 83, 69, 50, 49, 85,
       38, 72, 40, 77, 56, 67, 45, 38, 75, 71, 61, 70, 38, 67, 38, 63, 64,
       40, 40, 39, 66, 44, 78, 77, 83, 82, 85, 85, 48, 69])

In [16]:
np.random.randint(35,86,(5,5))

array([[42, 37, 78, 77, 49],
       [72, 78, 79, 74, 81],
       [58, 47, 64, 45, 48],
       [60, 69, 82, 56, 56],
       [80, 44, 70, 83, 52]])